---
:master_goods:
  :method:
  - count
  - search
  - upload
  :prefix: goods
  :fields: id,name,jan_code
:master_stock:
  :method:
  - count
  - search
  :prefix: stock
  :fields: goods_id,quantity,allocation_quantity,defective_quantity,remaining_order_quantity,out_quantity,free_quantity,advance_order_quantity,advance_order_allocation_quantity,advance_order_free_quantity
:master_mailtag:
  :method:
  - count
  - search
  :prefix: mail_tag
  :fields: id,month,name,note,message1,message2,message3,message4,message5,message6
:master_goodstag:
  :method:
  - count
  - search
  :prefix: goods_tag
  :fields: goods_id,name
:master_supplier:
  :method:
  - count
  - search
  :prefix: supplier
  :fields: id,name,post
:master_wholesale:
  :method:
  - count
  - search
  :prefix: wholesale
  :fields: id,name,post_name,destination_no
:master_stockiohistory:
  :method:
  - count
  - search
  :prefix: stock_io_history
  :fields: id,shop_id,goods_id,date,before_stock_quantity,after_stock_quantity,before_bad_stock_quantity,after_bad_stock_quantity,quantity,cut_form_id,io_flag,io_type_id,io_type_name,reason,pic_id,pic_name
:master_pagebase:
  :method:
  - count
  - search
  :prefix: page_base
  :fields: goods_id,goods_name
:master_pagebasevariationoroption:
  :method:
  - count
  - search
  :prefix: page_base_v_o
  :fields: goods_id,option_category,option_name,horizontal_value,vertical_value,horizontal_name,vertical_name,type,display_order
:master_shop:
  :method:
  - count
  - search
  - checkconnect
  - create
  - update
  :prefix: shop
  :fields: id,name,kana,abbreviated_name,handling_goods_name,note,mall_id,authorization_type_id,authorization_type_name,tax_id,tax_name,currency_unit_id,currency_unit_name,tax_calculation_sequence_id,type_id,deleted_flag
:master_goodsimage:
  :method:
  - count
  - search
  :prefix: goods_image
  :fields: id,goods_id,file_name,url_http,url_https,size,width,height,alt,convert_flg,display_order,status
:master_goodsimagetag:
  :method:
  - count
  - search
  :prefix: goods_image_tag
  :fields: id,goods_image_id,image_tag_id
:master_goodscategory:
  :method:
  - count
  - search
  :prefix: goods_category
  :fields: id,goods_id,mall_id,mall_category_id,text
:login_user:
  :method:
  - info
:login_company:
  :method:
  - info
:system_credittype:
  :method:
  - info
:system_creditauthorizationcenter:
  :method:
  - info
:system_creditapprovaltype:
  :method:
  - info
:system_order:
  :method:
  - info
:system_ordercondition:
  :method:
  - info
:system_delivery:
  :method:
  - info
:system_fraction:
  :method:
  - info
:system_returnedreason:
  :method:
  - info
:system_canceltype:
  :method:
  - info
:system_orderstatus:
  :method:
  - info
:system_importantcheck:
  :method:
  - info
:system_confirmcheck:
  :method:
  - info
:system_customertype:
  :method:
  - info
:system_deposittype:
  :method:
  - info
:system_iotype:
  :method:
  - info
:system_select:
  :method:
  - info
:system_paymentmethod:
  :method:
  - info
:system_payout:
  :method:
  - info
:system_socialinsurance:
  :method:
  - info
:system_goodstype:
  :method:
  - info
:system_goodsstatus:
  :method:
  - info
:system_merchandise:
  :method:
  - info
:system_importtype:
  :method:
  - info
:system_forwardingmethod:
  :method:
  - info
:system_tax:
  :method:
  - info
:system_itemname:
  :method:
  - info
:system_pagestatus:
  :method:
  - info
:system_authorizationtype:
  :method:
  - info
:system_currencyunit:
  :method:
  - info
:system_que:
  :method:
  - count
  - search
  :prefix: que
  :fields: id,method_name,shop_id,upload_name,client_file_name,file_name,status_id,message
:system_mall:
  :method:
  - count
  - search
  :prefix: mall
  :fields: id,name,kana,note,country_id
:system_imagetag:
  :method:
  - count
  - search
  :prefix: image_tag
  :fields: id,mall_id,mall_sub_id,text,auto_register_no,display_order
:system_mallcategory:
  :method:
  - count
  - search
  :prefix: mall_category
  :fields: id,mall_id,code,parent_mall_category_id,name,full_name
:system_deliverydate:
  :method:
  - info
  :prefix: delivery_date
  :fields: id,name,days,note
:receiveorder_uploadpattern:
  :method:
  - info
:receiveorder_base:
  :method:
  - count
  - search
  - update
  - upload
  - receipted
  - shipped
  - labelprinted
  - divide
  :prefix: receive_order
  :fields: shop_id,id,shop_cut_form_id,date,import_date,important_check_id,important_check_name,confirm_check_id,confirm_check_name,confirm_ids,mail_status,gruoping_tag,import_type_id,import_type_name,cancel_type_id,cancel_type_name,cancel_date,closed_after_edit_date,order_status_id,order_status_name,delivery_id,delivery_name,payment_method_id,payment_method_name,total_amount,tax_amount,charge_amount,delivery_fee_amount,other_amount,point_amount,goods_amount,deposit_amount,deposit_type_id,deposit_type_name,deposit_date,foreign_total_amount,foreign_tax_amount,foreign_charge_amount,foreign_delivery_fee_amount,foreign_other_amount,foreign_goods_amount,foreign_deposit_amount,note,include_possible_order_id,include_to_order_id,multi_delivery_parent_order_id,multi_delivery_parent_flag,statement_delivery_instruct_printing_date,statement_delivery_printing_date,statement_delivery_text,send_date,send_plan_date,send_sequence,worker_text,picking_instruct,picking_min_supplier_id,picking_min_goods_id,label_print_date,label_print_flag,hope_delivery_date,hope_delivery_time_slot_id,hope_delivery_time_slot_name,delivery_method_id,delivery_method_name,seal1_id,seal1_name,seal2_id,seal2_name,seal3_id,seal3_name,seal4_id,seal4_name,business_office_stop_id,business_office_stop_name,invoice_id,invoice_name,temperature_id,temperature_name,business_office_name,gift_flag,delivery_cut_form_id,delivery_cut_form_note,credit_type_id,credit_type_name,credit_approval_no,credit_approval_amount,credit_approval_type_id,credit_approval_type_name,credit_approval_date,credit_approval_rate,credit_number_payments,credit_authorization_center_id,credit_authorization_center_name,credit_approval_fax_printing_date,customer_type_id,customer_type_name,customer_id,purchaser_name,purchaser_kana,purchaser_zip_code,purchaser_address1,purchaser_address2,purchaser_tel,purchaser_fax,purchaser_mail_address,consignee_name,consignee_kana,consignee_zip_code,consignee_address1,consignee_address2,consignee_tel,consignee_fax,reminder_start_date,reminder_last_date,reminder_count,important_check_pic_id,important_check_pic_name,pic_id,pic_name,send_pic_id,send_pic_name,deleted_flag,creation_date,last_modified_date,last_modified_null_safe_date,creator_id,creator_name,last_modified_by_id,last_modified_by_null_safe_id,last_modified_by_name,last_modified_by_null_safe_name
:receiveorder_option:
  :method:
  - count
  - search
  :prefix: receive_order_option
  :fields: receive_order_id,single_word_memo,message,noshi,rapping,1,2,3,4,5,6,7,8,9,10,received_time_shop_coupon,received_time_mall_coupon,deleted_flag,creation_date,last_modified_date,last_modified_null_safe_date,creator_id,creator_name,last_modified_by_id,last_modified_by_null_safe_id,last_modified_by_name,last_modified_by_null_safe_name
:receiveorder_row:
  :method:
  - count
  - search
  :prefix: receive_order_row
  :fields: receive_order_id,shop_cut_form_id,no,shop_row_no,goods_id,goods_name,quantity,unit_price,wholesale_retail_ratio,goods_option
:receiveorder_forwardingagent:
  :method:
  - count
  - search
  :prefix: forwarding_agent
  :fields: id,type,type_id,type_name,display_order,deleted_flag
:receiveorder_confirm:
  :method:
  - count
  - search
  - update
  :prefix: confirm
  :fields: id,name,display_order,html,value,valid_flag
:receiveorder_paymentdeliveryconvert:
  :method:
  - count
  - search
  :prefix: payment_delivery_convert
  :fields: text,type,multi_id,delivery_id,deleted_flag,creation_date,last_modified_date,creator_id,creator_name,last_modified_by_id,last_modified_by_name
:notice_execution:
  :method:
  - add
  - count
  - search
  :prefix: execution_notice
  :fields: id,success,title,content,read,creation_date,last_modified_date
